import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const joyfish = localFont({
  src: "../public/assets/Joyfish - Demo.ttf",
  variable: "--font-joyfish",
});

const mosseta = localFont({
  src: "../public/assets/mosseta/Mosseta-Regular.otf",
  variable: "--font-mosseta",
});

export const metadata: Metadata = {
  title: "The Bling Bangles",
  description: "Generated by create next app",
};

import SmoothScroll from "@/components/SmoothScroll";
import Loader from "@/components/Loader";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${joyfish.variable} ${mosseta.variable} antialiased bg-white selection:bg-[#E6C78B] selection:text-white`}
      >

        <Loader />
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
